### ISSUE TITLE
spaRSS-DecSync and Flym-DecSync

### ISSUE THREAD

**Issue by plr20** [39aldo39/Flym-DecSync#1]
What's the difference between this and spaRSS-DecSync?

**Comment by 39aldo39** [comment]
As the names state, spaRSS DecSync is based on spaRSS and Flym DecSync is based on Flym. spaRSS has been unmaintained for a while and when I started with Flym DecSync, Flym was still active. However, Flym is now archived as well, making both apps similar, although I personally like Flym more. I still published it as I already implemented it, but adding DecSync support to an active app is still preferable. See also 39aldo39/spaRSS-DecSync#18.
